### ISSUE TITLE
having an interactive `docker run` or `docker exec` version of an eri image open breaks the website

### ISSUE THREAD

**Issue by RZachLamberty** [ElderResearch/gpu_launch_app#4]
to reproduce:

```
docker run --runtime nvidia -e NVIDIA_VISIBLE_DEVICES=0 --rm -it -p 8889:8888 -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v $HOME:$HOME:rw -v /data:/data:rw -u $( id -u $USER ):$( id -g $USER ) eri_dev bash
```

then try and reload the app at http://eri-gpu:5000/

**Comment by semperstew** [comment]
@enmyj Can you investigate this after we merge #3 ?

**Comment by enmyj** [comment]
I tested a few different ways of launching/connecting to running containers interactively and none of them broke the webapp. I think we're good to close this.
